TARGET_EXEC := main
CPPC := clang++
STD = c++23
# CPPCFLAGS := -std=$(STD) -march=native -Wall -Wextra -Wpedantic -Werror -O3
# CPPCFLAGS := -std=$(STD) -march=native -Wall -Wextra -Wpedantic -O3
CPPCFLAGS := -std=$(STD) -march=native -Wall -Wextra -Wpedantic -Og -ggdb3 -fsanitize=address,leak
# CPPCFLAGS := -std=$(STD) -march=native -Wall -Wextra -Wpedantic -O0 -ggdb3 -fsanitize=address,leak

# -Og behaves the similarly to -O1 in terms of a optimizations apart from
# select flags.
# See: https://gcc.gnu.org/onlinedocs/gcc/Optimize-Options.html#index-Og
# CPPCFLAGS := -std=$(STD) -march=native -Wall -Wextra -Wpedantic -Og -ggdb3

# -Og, meaning the -O1 optimizations with additional debuging into; with inlining disabled
# CPPCFLAGS := -std=$(STD) -march=native -Wall -Wextra -Wpedantic -Werror -Og -ggdb3 -fno-inline
#
# CPPCFLAGS := -std=$(STD) -march=native -Wall -Wextra -Wpedantic -Werror -O0 -ggdb3
LDFLAGS := 

BUILD_DIR := ./build
CACHE_DIR := ./.cache
SRC_DIRS := ./src

# Searching for source files inside the source directories using `find`.
# `find` is recursive by default.
SRCS := $(shell find $(SRC_DIRS) -name '*.cpp')
# Generating paths for corresponding object files by appending a .o suffix
# at the end of each source file. Placing them inside the BUILD_DIR.
OBJS := $(SRCS:%=$(BUILD_DIR)/%.o)

# Generating the paths for Makefiles generated by the GCC to include in the
# end of this Makefile. The dependency files are important as they define
# targets for each object file that depends not only on the source file
# but also on the headers. Without the dependency files, Make would be able
# to tell that recompilation is needed if only header files were changed.
DEPS := $(OBJS:.o=.d)

# Looking for other directories within the SRC_DIRS to also include them.
# This will allow including the headers by file name only without specifying
# the full relative path for files up in hierarchy and for files lower in the
# hierarchy it enables specifying the path relative to the sources folder.
INC_DIRS := $(shell find $(SRC_DIRS) -type d)
# Generating the flags for including the directories which were found.
# Simply adding a prefix of "-I" to the end.
# Relevant reference: https://gcc.gnu.org/onlinedocs/gcc/Directory-Options.html#index-I
INC_FLAGS := $(addprefix -I,$(INC_DIRS))

# Flags for the C preprocessor that include the directories as well as
# command the compiler to generate Makefiles for the object files
# Relevant reference:
# https://gcc.gnu.org/onlinedocs/gcc-14.2.0/gcc/Preprocessor-Options.html#index-M
CPPFLAGS := $(INC_FLAGS) -MMD -MP

all: $(BUILD_DIR)/$(TARGET_EXEC)

# The final step that combines all of the object files together to generate the
# executable. The linking step.
$(BUILD_DIR)/$(TARGET_EXEC): $(OBJS)
	$(CPPC) $(CPPCFLAGS) $(OBJS) -o $@ $(LDFLAGS)

# General targets for all the object files, primarily used the first time
# to generate the .d Makefiles, afterwards the more specific targets defined
# in those Makefiles will be used (Make prioritizes more specific matches for
# targets instead of a wildcard).
$(BUILD_DIR)/%.cpp.o: %.cpp
	mkdir -p $(dir $@)
	$(CPPC) $(CPPFLAGS) $(CPPCFLAGS) -c $< -o $@

.PHONY: clean format lint generate_compile_commands
clean:
	if [ -d $(CACHE_DIR) ]; then \
		rm -r $(CACHE_DIR); \
	fi

	if [ -d $(BUILD_DIR) ]; then \
		rm -r $(BUILD_DIR); \
	fi

SOURCE_FILES_REGEX := ".*\.\(cpp\|hpp\|cc\|cxx\|ipp\)"
ALL_SOURCE_FILES := $(shell find $(SRC_DIRS) -regex $(SOURCE_FILES_REGEX) -type f)

# Config files
CLANG_FORMAT_STYLE_FILE = ./.clang-format
CLANG_TIDY_CONFIG_FILE = ./.clang-tidy

# Cache folders
CPPCHECK_CACHE_DIR = $(CACHE_DIR)/cppcheck

format:
	clang-format -style=file:$(CLANG_FORMAT_STYLE_FILE) -i $(ALL_SOURCE_FILES)
lint:
	clang-tidy --config-file=$(CLANG_TIDY_CONFIG_FILE) $(ALL_SOURCE_FILES)
	mkdir -p $(CPPCHECK_CACHE_DIR)
	cppcheck --std=$(STD) --enable=all --check-level=exhaustive -j $(shell nproc) --cppcheck-build-dir=$(CPPCHECK_CACHE_DIR) $(SRC_DIRS)
generate_compile_commands:
	bear -- make -j

# Including all the dependency Makefiles generated by GCC after the first
# run using the generic target defined about. The "-" is needed to ignore
# all the errors on the first run, as the Makefiles are not yet created,
# so there is nothing to include.
-include $(DEPS)
